name: CI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Invoke deployment hook
          uses: distributhor/workflow-webhook@v3
          with:
            webhook_url: ${{ secrets.WEBHOOK_URL }}