name: CI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Trigger Portainer stack webhook
        run: curl -X POST ${{ secrets.WEBHOOK_URL }}
            