name: CI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Setup pnpm
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.12
          cache: 'pnpm'
      - run: pnpm install
      - run: NX_SKIP_NX_CACHE=true pnpm nx build portfolio
      - uses: actions/upload-artifact@v4
        with:
          name: Dist
          path: ./dist
  docker_build:
    runs-on: ubuntu-latest
    name: Docker Image Build
    needs: [build]
    steps:
      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: Dist
          path: dist 
      - run: ls -R dist
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: dist
          file: ./dockerfile
          push: true
          tags: francoislongatte/portfolio:latest
  deploy:
    runs-on: ubuntu-latest
    name: Continuous Deployment
    needs: [docker_build]
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PORTFOLIO_SSH_HOST }}
          username: ${{ secrets.PORTFOLIO_SSH_PASSWORD }}
          password: ${{ secrets.PORTFOLIO_SSH_USERNAME }}
          port: 22
          script: |
            cd /srv/expressjs/;docker stop expressjs;docker rm expressjs;docker pull gvgodfrey/expressjs:latest;docker-compose up -d